spring:
  application:
    name: auth-service
    version: 1.0.0
  data:
    mongodb:
      host: localhost
      port: 27017
      database: wise_wallet

server:
  port: 8088

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true

springdoc:
  api-docs:
    path: /api/auth/v3/api-docs
  swagger-ui:
    path: /api/auth/swagger-ui.html