spring:
  application:
    name: user-service
    version: 1.0.0
  datasource:
    url: jdbc:postgresql://localhost:5432/wise_wallet?useUnicode=yes&characterEncoding=UTF-8
    username: ${EVENTSTORE_USERNAME}
    password: ${EVENTSTORE_PASSWORD}
  data:
    mongodb:
      host: localhost
      port: 27017
      database: wise_wallet

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true

springdoc:
  api-docs:
    path: /api/users/v3/api-docs
  swagger-ui:
    path: /api/users/swagger-ui.html

event-store:
  snapshotting:
    USER:
      enabled: true
      nth-event: 8