spring:
  application:
    name: user-service
  datasource:
    urL: jdbc:postgresql://localhost:5432/wise_wallet?useUnicode=yes&characterEncoding=UTF-8
    username: ${EVENTSTORE_USERNAME}
    password: ${EVENTSTORE_PASSWORD}
  data:
    mongodb:
      host: localhost
      port: 27017
      database: wise_wallet
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true

event-store:
  snapshotting:
    USER:
      enabled: true
      nth-event: 8