spring:
  datasource:
    urL: jdbc:postgresql://localhost:5432/wise_wallet?useUnicode=yes&characterEncoding=UTF-8
    username: ${EVENTSTORE_USERNAME}
    password: ${EVENTSTORE_PASSWORD}
  data:
    mongodb:
      host: localhost
      port: 27017
      database: wise_wallet

event-store:
  snapshotting:
    REMINDER:
      enabled: true
      nth-event: 8

kafka:
  topics:
    name: reminder-events