server:
  port: 8087

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081
    fetch-registry: true
    register-with-eureka: true

spring:
  datasource:
    urL: jdbc:postgresql://localhost:5432/wise_wallet?useUnicode=yes&characterEncoding=UTF-8
    username: ${EVENTSTORE_USERNAME}
    password: ${EVENTSTORE_PASSWORD}
  data:
    mongodb:
      host: localhost
      port: 27017
      database: wise_wallet

springdoc:
  swagger-ui:
    path: "/"

event-store:
  snapshotting:
    BUDGET:
      enabled: true
      nth-event: 8

kafka:
  topics:
    name: budget-events