spring:
  application:
    name: category-service
  datasource:
    urL: jdbc:postgresql://localhost:5432/wise_wallet?useUnicode=yes&characterEncoding=UTF-8
    username: ${EVENTSTORE_USERNAME}
    password: ${EVENTSTORE_PASSWORD}
  data:
    mongodb:
      host: localhost
      port: 27017
      database: wise_wallet

server:
  port: 8085

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true

event-store:
  snapshotting:
    CATEGORY:
      enabled: true
      nth-event: 8